services:
  elysia-backend:
    build: .
    container_name: elysia-evernight
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.evernight-backend.rule=Host(`${DOMAIN}`)" 
      - "traefik.http.routers.evernight-backend.entrypoints=websecure"
      - "traefik.http.routers.evernight-backend.tls.certresolver=myresolver"
      - "traefik.http.services.evernight-backend.loadbalancer.server.port=21000" 
    networks : 
      - elysia-network
networks:
  elysia-network:
    external: true
