services:
  elysia-backend:
    build: .
    container_name: elysia-evernight
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elysia.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.elysia.entrypoints=websecure"
      - "traefik.http.routers.elysia.tls.certresolver=myresolver"
      - "traefik.http.services.elysia.loadbalancer.server.port=21000"
    networks : 
      - elysia-network
networks:
  elysia-network:
    external: true
